---
# tasks file for perf-testing

- name: Include OS-specific vars
  include_vars: "{{ ansible_os_family }}_jws.yml"

- name: Execute OS-specific JWS installation instructions
  include_tasks: "{{ ansible_os_family }}-jws-install.yml"
  when: inventory_hostname in groups['jws']

- name: Execute JMeter installation instructions
  include_tasks: jmeter.yml
  when: inventory_hostname in groups['jmeter']

- name: Start JMeter
  include_tasks: perform_perftesting.yml
  when: inventory_hostname in groups['jmeter']
