---
# windows-specific tasks file for perf-testing
- name: "Ensure {{ jws_unzip_path }} exists"
  win_file:
    path: "{{ jws_unzip_path }}"
    state: directory

- name: "Download JWS zips"
  win_get_url:
    dest: "{{ jws_unzip_path }}"
    url: "{{ item }}"
  with_items: "{{ jws_urls }}"

- name: "Unzip all zips"
  win_unzip:
    src: "{{ jws_unzip_path }}/{{ item | basename }}"
    dest: "{{ jws_unzip_path }}"
  with_items: "{{ jws_urls }}"

- name: "Copy certs to JWS"
  win_copy:
    src: ssl
    dest: "{{ jws_unzip_path }}"

- name: "Template server.xml"
  win_template:
    dest: "{{ jws_unzip_path }}/jws-5.0/tomcat/conf/server.xml"
    src: "{{ jws_ssl_conf }}.xml"

# This is a workaround; we have to add a windows newline into the startagent script
- name: "Copy startAgent.bat into perfmon server agent"
  win_copy:
    src: startAgent.bat
    dest: "{{ jws_unzip_path }}/{{ jws_agent_dir_name }}/startAgent.bat"

- name: "Start perfmon ServerAgent in {{ jws_unzip_path }}/{{ jws_agent_url | basename | splitext | first }}"
  win_command: "startAgent.bat --tcp-port 8000 --udp-port 8000"
  args:
    chdir: "{{ jws_unzip_path }}/{{ jws_agent_dir_name }}"
  async: 1
  poll: 0

- name: "Start JWS Server"
  win_command: "startup.bat"
  args:
    chdir: "{{ jws_unzip_path }}/jws-5.0/tomcat/bin/"
  async: 1
  poll: 0
