---
# vars file for perf-testing

# JWS platform-independent vars
jws_urls:
  - "{{ lookup('env','URL_BASE') }}/5.0.0/jws-5.0.0-application-server.zip"
  - "{{ lookup('env','URL_BASE') }}/5.0.0/jws-5.0.0-application-server-RHEL7-x86_64.zip"
  - "{{ lookup('env','URL_BASE') }}/5.0.1/jws-5.0.1-application-server.zip"
  - "{{ jws_agent_url }}"
jws_agent_url: "https://github.com/undera/perfmon-agent/releases/download/2.2.3/ServerAgent-2.2.3.zip"
jws_agent_dir_name: "{{ jws_agent_url | basename | splitext | first }}"
# The ssl conf that is used; this should correspond to a template xml file
# That means it can be apr, or jsse (since apr.xml and jsse.xml are in templates)
jws_ssl_conf: "{{ lookup('env','SSL_CONF') | default('jsse', true) }}"

# JMeter vars
jmeter_unzip_path: "/tmp/jmeter"
jmeter_url: "https://www-us.apache.org/dist/jmeter/binaries/apache-jmeter-5.0.zip"
jmeter_plugin_urls:
  - "https://jmeter-plugins.org/files/packages/jpgc-perfmon-2.1.zip"
  - "https://jmeter-plugins.org/files/packages/jpgc-cmd-2.2.zip"

jmeter_dir_name: "{{ jmeter_url | basename | splitext | first }}"
jmeter_root_dir_path: "{{ jmeter_unzip_path }}/{{ jmeter_dir_name }}"
jmeter_out_dir: "{{ jmeter_unzip_path }}/out"
# IP address which we want to stress test
jmeter_target_ip: "{{ lookup('env','JMETER_TARGET') }}"
